FROM python:3

ARG DEBIAN_FRONTEND=noninteractive

ENV LANG C.UTF-8-SIG

RUN apt-get update -y
# RUN apt-get install -y python3
# RUN apt-get install -y python3-pip

COPY . C:/Users/Redtable/Desktop/hojin/docker_ex

WORKDIR C:/Users/Redtable/Desktop/hojin/docker_ex

# 구글 크롬 다운로드
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN apt -y install ./google-chrome-stable_current_amd64.deb

# 구글 크롬 드라이버
RUN wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/` curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip
RUN mkdir chrome
RUN unzip /tmp/chromedriver.zip chromedriver -d /usr/src/chrome
# Konlpy에 필요한 java 환경 설치
# RUN apt-get install -y default-jdk default-jre

RUN pip3 install pip --upgrade
RUN pip3 install selenium
RUN pip3 install jupyter
RUN pip3 install pandas
RUN pip3 install BeautifulSoup4
RUN pip3 install PyMySQL
RUN pip3 install --upgrade --ignore-installed pip setuptools
RUN pip3 install tqdm
RUN pip3 install openpyxl



CMD ["python3", "crawling_recipe.py"]
